version: '3.8'

services:
  user-service:
    build:
      context: ./UserService
    container_name: user-service
    ports:
      - "8000:8000"                # Expose UserService on localhost:8000
    env_file:
      - ./UserService/.env
    restart: unless-stopped

  course-service:
    build:
      context: ./CourseService
    container_name: course-service
    ports:
      - "8001:8000"                # Expose CourseService on localhost:8001 (container listens on 8000)
    env_file:
      - ./CourseService/.env
    restart: unless-stopped
